version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: civic_issues
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://postgres:5432/civic_issues
      JWT_SECRET: mySecretKey
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: mvn spring-boot:run

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data:
