server:
  port: 8080

spring:
  application:
    name: civic-issue-system
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/civic_issues}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:iamvishwajeet1010@gmail.com}
    password: ${MAIL_PASSWORD:gzzm mcxd nwnb zqsf}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.civic.civicissuesystem: DEBUG
    org.springframework.security: DEBUG
